export enum ResponseCode {
  SUCCESS = 200,
  UNAUTHORIZED = 401,
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  PERMISSION = 403,
  DATA_INVALID = 422,
  SERVER_ERROR = 500,
}

export const DEFAULT_PAGE_PAGINATION = 1;
export const DEFAULT_LIMIT_PAGINATION = 10;